name = "Brillouin"
uuid = "23470ee3-d0df-4052-8b1a-8cbd6363e7f0"
authors = ["Thomas Christensen <tchr@mit.edu> and contributors"]
version = "0.5.30"

[deps]
Bravais = "ada6cbde-b013-4edf-aa94-f6abe8bd6e6b"
DirectQhull = "c3f9d41a-afcb-471e-bc58-0b8d83bd86f4"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Spglib = "f761d5c5-86db-4880-b97f-9680a7cccfb5"

[extensions]
BrillouinMakieExt = "Makie"
BrillouinPlotlyJSExt = "PlotlyJS"
BrillouinSpglibExt = "Spglib"

[compat]
Bravais = "0.2.4"
DirectQhull = "0.2.1"
DocStringExtensions = "0.8, 0.9"
Makie = "0.22, 0.23, 0.24.2"
PlotlyJS = "0.18"
PrecompileTools = "1"
Reexport = "1"
Requires = "1.1"
Spglib = "0.8, 0.9, 1"
StaticArrays = "1.2"
julia = "1.6"

[extras]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Spglib = "f761d5c5-86db-4880-b97f-9680a7cccfb5"
